"""empty message

Revision ID: cbab0c3a4b09
Revises: 8aa98c300167
Create Date: 2023-05-10 05:29:42.905908

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cbab0c3a4b09"
down_revision = "8aa98c300167"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
