"""empty message

Revision ID: c63254b7fcf5
Revises: 62d24484c5b6
Create Date: 2023-05-10 06:36:32.678051

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c63254b7fcf5"
down_revision = "62d24484c5b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
