"""empty message

Revision ID: 7f806992adde
Revises: ab4278916842
Create Date: 2023-05-04 22:01:56.727459

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "7f806992adde"
down_revision = "ab4278916842"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("share_uuid", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.Column("spymaster", sa.Boolean(), nullable=True),
        sa.Column("operative", sa.Boolean(), nullable=True),
        sa.Column("team_color", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["room"], ["rooms.id"], name="fk_player_type_rooms_id_room"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room"],
            ["rooms.id"],
            name="fk_rooms_users_rooms_room_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_rooms_users_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_name", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=24), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("game", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["game"], ["game.id"], name="fk_cards_game_id_game"),
        sa.ForeignKeyConstraint(
            ["room_name"], ["game.id"], name="fk_cards_game_id_room_name"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("player")
    op.drop_table("player_log")
    op.add_column("game", sa.Column("status", sa.String(length=1024), nullable=False))
    op.add_column("game", sa.Column("turn", sa.String(length=24), nullable=False))
    op.add_column("game", sa.Column("room", sa.Integer(), nullable=True))
    op.drop_constraint("fk_game_player_id_players", "game", type_="foreignkey")
    op.create_foreign_key("fk_game_rooms_id_room", "game", "rooms", ["room"], ["id"])
    op.drop_column("game", "created_at")
    op.drop_column("game", "updated_at")
    op.drop_column("game", "players")
    op.drop_column("game", "current_turn")
    op.drop_column("game", "finished")
    op.drop_column("game", "room_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game", sa.Column("room_name", sa.VARCHAR(length=255), nullable=False)
    )
    op.add_column("game", sa.Column("finished", sa.BOOLEAN(), nullable=True))
    op.add_column(
        "game", sa.Column("current_turn", sa.VARCHAR(length=24), nullable=True)
    )
    op.add_column("game", sa.Column("players", sa.INTEGER(), nullable=True))
    op.add_column("game", sa.Column("updated_at", sa.DATETIME(), nullable=True))
    op.add_column("game", sa.Column("created_at", sa.DATETIME(), nullable=True))
    op.drop_constraint("fk_game_rooms_id_room", "game", type_="foreignkey")
    op.create_foreign_key(
        "fk_game_player_id_players", "game", "player", ["players"], ["id"]
    )
    op.drop_column("game", "room")
    op.drop_column("game", "turn")
    op.drop_column("game", "status")
    op.create_table(
        "player_log",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("player", sa.INTEGER(), nullable=True),
        sa.Column("spy_master_keyword", sa.VARCHAR(length=255), nullable=False),
        sa.Column("spy_master_keyword_count", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player"], ["player.id"], name="fk_player_log_player_id_player"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("unique_identifier", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("active_from", sa.DATETIME(), nullable=True),
        sa.Column("browser_details", sqlite.JSON(), nullable=True),
        sa.Column("player_type", sa.VARCHAR(length=9), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("cards")
    op.drop_table("rooms_users")
    op.drop_table("player_type")
    op.drop_table("rooms")
    # ### end Alembic commands ###
