"""empty message

Revision ID: 8aa98c300167
Revises: 2105958436b6
Create Date: 2023-05-10 05:20:27.911620

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8aa98c300167"
down_revision = "2105958436b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("sequence", sa.Integer(), nullable=True))
    op.add_column("cards", sa.Column("is_revealed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "is_revealed")
    op.drop_column("cards", "sequence")
    # ### end Alembic commands ###
