"""empty message

Revision ID: ab4278916842
Revises: 
Create Date: 2023-05-03 09:32:02.662341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab4278916842"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_identifier", sa.String(length=1024), nullable=False),
        sa.Column("card_data", sa.String(length=255), nullable=False),
        sa.Column("is_revealed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unique_identifier", sa.String(length=1024), nullable=False),
        sa.Column("active_from", sa.DateTime(), nullable=True),
        sa.Column("browser_details", sa.JSON(none_as_null=True), nullable=True),
        sa.Column(
            "player_type",
            sa.Enum("operative", "spymaster", name="playertype"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_name", sa.String(length=255), nullable=False),
        sa.Column("finished", sa.Boolean(), nullable=True),
        sa.Column("current_turn", sa.String(length=24), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("players", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["players"], ["player.id"], name="fk_game_player_id_players"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player", sa.Integer(), nullable=True),
        sa.Column("spy_master_keyword", sa.String(length=255), nullable=False),
        sa.Column("spy_master_keyword_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player"], ["player.id"], name="fk_player_log_player_id_player"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_log")
    op.drop_table("game")
    op.drop_table("users")
    op.drop_table("player")
    op.drop_table("game_stats")
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
