"""empty message

Revision ID: e8aaf4b987f6
Revises: 
Create Date: 2023-05-08 06:20:40.017840

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8aaf4b987f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_identifier", sa.String(length=1024), nullable=False),
        sa.Column("card_data", sa.String(length=255), nullable=False),
        sa.Column("is_revealed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("share_uuid", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=1024), nullable=False),
        sa.Column("turn", sa.String(length=24), nullable=False),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["room"], ["rooms.id"], name="fk_game_rooms_id_room"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.Column("spymaster", sa.Boolean(), nullable=True),
        sa.Column("operative", sa.Boolean(), nullable=True),
        sa.Column("team_color", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["room"], ["rooms.id"], name="fk_player_type_rooms_id_room"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room"],
            ["rooms.id"],
            name="fk_rooms_users_rooms_room_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_rooms_users_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_name", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=24), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("game", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["game"], ["game.id"], name="fk_cards_game_id_game"),
        sa.ForeignKeyConstraint(
            ["room_name"], ["game.id"], name="fk_cards_game_id_room_name"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cards")
    op.drop_table("rooms_users")
    op.drop_table("player_type")
    op.drop_table("game")
    op.drop_table("users")
    op.drop_table("rooms")
    op.drop_table("game_stats")
    op.drop_table("dummy_model")
    # ### end Alembic commands ###
