"""empty message

Revision ID: 8e1457ef0357
Revises: f87f828503fa
Create Date: 2023-05-10 09:47:00.948039

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e1457ef0357"
down_revision = "f87f828503fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
