"""empty message

Revision ID: 62d24484c5b6
Revises: cbab0c3a4b09
Create Date: 2023-05-10 05:52:26.084894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62d24484c5b6"
down_revision = "cbab0c3a4b09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
