"""empty message

Revision ID: 2fe1202af159
Revises: 08e21a17084c
Create Date: 2023-05-08 19:42:34.709483

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fe1202af159"
down_revision = "08e21a17084c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
