"""Added initial table

Revision ID: 98a6fbb21f47
Revises: 2b7380507a71
Create Date: 2023-04-29 22:18:33.986231

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "98a6fbb21f47"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_identifier", sa.String(length=1024), nullable=False),
        sa.Column("card_data", sa.String(length=255), nullable=False),
        sa.Column("is_revealed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unique_identifier", sa.String(length=1024), nullable=False),
        sa.Column("active_from", sa.DateTime(), nullable=True),
        sa.Column("browser_details", sa.JSON(none_as_null=True), nullable=True),
        sa.Column(
            "player_type",
            sa.Enum("operative", "spymaster", name="playertype"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player", sa.Integer(), nullable=True),
        sa.Column("spy_master_keyword", sa.String(length=255), nullable=False),
        sa.Column("spy_master_keyword_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player"],
            ["player.id"],
            name="fk_player_log_player_id_player",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_log")
    op.drop_table("player")
    op.drop_table("game_stats")
    op.drop_table("game")
    # ### end Alembic commands ###
