"""empty message

Revision ID: 2105958436b6
Revises: 2fe1202af159
Create Date: 2023-05-08 19:43:23.739093

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2105958436b6"
down_revision = "2fe1202af159"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(length=2048), nullable=False),
        sa.Column("identifier", sa.String(length=1024), nullable=False),
        sa.Column("generated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["game"], ["game.id"], name="fk_game_log_game_id_game"),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name="fk_game_log_users_id_generated_by"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_log")
    # ### end Alembic commands ###
